export { default as About } from './about/About';
export { default as Benefits } from './benefits/Benefits';
export { default as Contact } from './contact/Contact';
export { default as Features } from './features/Features';
export { default as Footer } from './footer/Footer';
export { default as Form } from './form/Form';
export { default as Gallery } from './gallery/Gallery';
export { default as Hero } from './hero/Hero';
export { default as Testimonials } from './testimonials/Testimonials';
